name: Build and Package .deb

on:
  push:
    tags:
      - 'v*.*.*'



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Confirm GH_TOKEN is available
        run: echo "GH_TOKEN is set"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Build .deb
        run: npm run package
        env:
            GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cribarth-music-player-deb
          path: dist/*.deb

